import { constants, type Stats } from "node:fs";
import { lstat, open, readFile, type FileHandle } from "node:fs/promises";
import { dirname } from "node:path";
import type { RedactedProbeRecord, ProbeRecordStore } from "./contracts.js";
import type { CallbackObservation, CallbackObservationPort } from "../wechat/callback-service.js";
import type { ProbeRedactor } from "./redaction.js";

const HMAC = /^h1:[A-Za-z0-9_-]{43}$/; const SHA256 = /^[a-f0-9]{64}$/;
const FAILURE_CODES = new Set(["FETCH_URL_REJECTED", "FETCH_ADDRESS_REJECTED", "FETCH_TLS_FAILED", "FETCH_NETWORK_FAILED", "FETCH_CONNECT_TIMEOUT", "FETCH_HEADERS_TIMEOUT", "FETCH_TOTAL_TIMEOUT", "FETCH_HTTP_NON2XX", "FETCH_AUTH_OR_CAPTCHA", "FETCH_MIME_INVALID", "FETCH_CONTENT_ENCODING_INVALID", "FETCH_REDIRECT_REJECTED", "FETCH_BODY_LIMIT", "FETCH_PARSE_FAILED", "FETCH_BELOW_500_CODEPOINTS", "WX_URL_UNPARSEABLE", "FETCH_FAILED", "QUEUE_FULL", "FEEDBACK_FAILED", "WX_FEEDBACK_WINDOW_CLOSED", "WX_FEEDBACK_PROBE_CONFLICT", "WX_FEEDBACK_URL_REJECTED", "WX_FEEDBACK_TOKEN_REJECTED", "WX_FEEDBACK_REDIRECT_REJECTED", "WX_FEEDBACK_RESPONSE_LIMIT", "WX_FEEDBACK_RESPONSE_INVALID", "WX_FEEDBACK_TIMEOUT", "WX_FEEDBACK_NETWORK_FAILED", "WX_FEEDBACK_HTTP_FAILED", "WX_FEEDBACK_PLATFORM_REJECTED"]);
const stages = new Set<RedactedProbeRecord["stage"]>(["callback_rejected", "callback_ignored", "accepted", "fetching", "extracted", "fetch_failed", "feedback_sent", "feedback_rejected", "reopened"]);
const keys = ["schemaVersion", "probeHmac", "callbackTraceHmac", "at", "stage", "receiptHmac", "senderHmac", "urlHmac", "host", "signatureValid", "callbackKind", "callbackSource", "duplicateCallback", "linkUrlParsed", "ackLatencyMs", "httpStatus", "bodyCodePoints", "bodySha256", "failureCode", "feedbackChannel", "feedbackResult"] as const;
const euid = (): number => process.geteuid?.() ?? process.getuid?.() ?? -1;
export interface RecordFileOperations { lstat(path: string): Promise<Stats>; open(path: string, flags: number, mode: number): Promise<FileHandle>; readFile(path: string, encoding: BufferEncoding): Promise<string>; }
const nativeOps: RecordFileOperations = { lstat, open, readFile };
export class ProbeEvidenceError extends Error { constructor(readonly code: "EVIDENCE_MISSING" | "EVIDENCE_CORRUPT") { super(code); } }
const iso = (value: unknown): value is string => typeof value === "string" && Number.isFinite(Date.parse(value)) && new Date(value).toISOString() === value;
const hmac = (value: unknown): value is string => typeof value === "string" && HMAC.test(value);
function snapshot(value: unknown): Record<string, unknown> | null { try { if (value === null || typeof value !== "object") return null; const proto = Object.getPrototypeOf(value); if (proto !== Object.prototype && proto !== null) return null; const descriptors = Object.getOwnPropertyDescriptors(value); if (Object.getOwnPropertySymbols(descriptors).length !== 0) return null; const out: Record<string, unknown> = Object.create(null); for (const [key, descriptor] of Object.entries(descriptors)) { if (!descriptor.enumerable || !("value" in descriptor)) return null; out[key] = descriptor.value; } return out; } catch { return null; } }
/** Validates then copies only the portable allow-list; callers never reach JSON.stringify. */
export function canonicalizeRecord(input: unknown): RedactedProbeRecord {
  const v = snapshot(input); if (v === null || !Object.keys(v).every((key) => (keys as readonly string[]).includes(key))) throw new Error("invalid redacted record");
  if (v.schemaVersion !== 1 || !iso(v.at) || typeof v.stage !== "string" || !stages.has(v.stage as RedactedProbeRecord["stage"]) || (v.probeHmac !== null && !hmac(v.probeHmac)) || !hmac(v.callbackTraceHmac) || (v.receiptHmac !== null && !hmac(v.receiptHmac)) || (v.senderHmac !== null && !hmac(v.senderHmac))) throw new Error("invalid redacted record");
  const optional = (name: string, predicate: (value: unknown) => boolean): void => { if (name in v && !predicate(v[name])) throw new Error("invalid redacted record"); };
  optional("urlHmac", hmac); optional("host", (x) => x === "mp.weixin.qq.com"); optional("signatureValid", (x) => typeof x === "boolean"); optional("callbackKind", (x) => x === "link" || x === "text_link" || x === "unsupported" || x === "invalid"); optional("callbackSource", (x) => x === "wechat" || x === "admin_replay"); optional("duplicateCallback", (x) => typeof x === "boolean"); optional("linkUrlParsed", (x) => typeof x === "boolean"); optional("ackLatencyMs", (x) => typeof x === "number" && Number.isFinite(x) && x >= 0); optional("httpStatus", (x) => typeof x === "number" && Number.isInteger(x) && x >= 100 && x <= 599); optional("bodyCodePoints", (x) => typeof x === "number" && Number.isInteger(x) && x >= 0); optional("bodySha256", (x) => typeof x === "string" && SHA256.test(x)); optional("failureCode", (x) => typeof x === "string" && FAILURE_CODES.has(x)); optional("feedbackChannel", (x) => x === "passive_link" || x === "customer_service"); optional("feedbackResult", (x) => x === "sent" || x === "rejected" || x === "unsupported");
  const output: Record<string, unknown> = {}; for (const key of keys) if (key in v) output[key] = v[key]; return Object.freeze(output) as unknown as RedactedProbeRecord;
}
async function safeParent(path: string, ops: RecordFileOperations): Promise<void> { const p = await ops.lstat(dirname(path)); if (!p.isDirectory() || p.isSymbolicLink() || p.uid !== euid() || (p.mode & 0o022) !== 0) throw new Error("record storage rejected"); }
async function prior(path: string, ops: RecordFileOperations): Promise<Stats | null> { try { const s = await ops.lstat(path); if (!s.isFile() || s.isSymbolicLink() || s.uid !== euid()) throw new Error("record storage rejected"); return s; } catch (error: unknown) { if ((error as NodeJS.ErrnoException).code === "ENOENT") return null; throw error; } }
export async function createNdjsonProbeRecordStore(options: { readonly path: string; readonly operations?: RecordFileOperations }): Promise<ProbeRecordStore> {
  const ops = options.operations ?? nativeOps; await safeParent(options.path, ops); await prior(options.path, ops); let chain = Promise.resolve();
  async function appendNow(input: RedactedProbeRecord): Promise<void> { const record = canonicalizeRecord(input); await safeParent(options.path, ops); const before = await prior(options.path, ops); let handle: FileHandle | undefined; try { handle = await ops.open(options.path, constants.O_APPEND | constants.O_CREAT | constants.O_WRONLY | constants.O_NOFOLLOW | (before === null ? constants.O_EXCL : 0), 0o600); const after = await handle.stat(); if (!after.isFile() || after.uid !== euid() || after.nlink !== 1 || (before !== null && (before.dev !== after.dev || before.ino !== after.ino))) throw new Error("record storage rejected"); await handle.chmod(0o600); const bytes = Buffer.from(`${JSON.stringify(record)}\n`); const result = await handle.write(bytes); if (result.bytesWritten !== bytes.length) throw new Error("record write failed"); await handle.sync(); } finally { await handle?.close(); } }
  return { append(input) { let record: RedactedProbeRecord; try { record = canonicalizeRecord(input); } catch (error) { return Promise.reject(error); } const result = chain.then(() => appendNow(record)); chain = result.catch(() => undefined); return result; }, async *readAll() { let handle: FileHandle | undefined; try { await safeParent(options.path, ops); const before = await prior(options.path, ops); if (before === null) return; handle = await ops.open(options.path, constants.O_RDONLY | constants.O_NOFOLLOW, 0o600); const after = await handle.stat(); if (!after.isFile() || after.uid !== euid() || after.nlink !== 1 || before.dev !== after.dev || before.ino !== after.ino || (after.mode & 0o7777) !== 0o600) throw new ProbeEvidenceError("EVIDENCE_CORRUPT"); const data = await handle.readFile(); const raw = new TextDecoder("utf-8", { fatal: true }).decode(data); if (raw.length > 0 && !raw.endsWith("\n")) throw new ProbeEvidenceError("EVIDENCE_MISSING"); const lines = raw.split("\n"); for (let i = 0; i < lines.length - 1; i += 1) { const line = lines[i] ?? ""; const found = new Set<string>(); let duplicate = false; for (const match of line.matchAll(/"((?:[^"\\]|\\.)*)"\s*:/g)) { const key = match[1] ?? ""; if (found.has(key)) duplicate = true; found.add(key); } if (line === "" || duplicate) throw new ProbeEvidenceError("EVIDENCE_CORRUPT"); try { yield canonicalizeRecord(JSON.parse(line)); } catch { throw new ProbeEvidenceError("EVIDENCE_CORRUPT"); } } } catch (error: unknown) { if (error instanceof ProbeEvidenceError) throw error; if ((error as NodeJS.ErrnoException).code === "ENOENT") throw new ProbeEvidenceError("EVIDENCE_MISSING"); throw new ProbeEvidenceError("EVIDENCE_CORRUPT"); } finally { try { await handle?.close(); } catch { throw new ProbeEvidenceError("EVIDENCE_CORRUPT"); } } } };
}
export interface AuditHealth { readonly dropped: number; readonly failed: number; }
export interface AsyncRedactedWriter {
  record(record: RedactedProbeRecord): void;
  flush(): Promise<void>;
  readonly health: AuditHealth;
}
/** A bounded best-effort audit sink. `flush` creates a shutdown barrier without exposing raw records. */
export function createAsyncRedactedWriter(store: ProbeRecordStore): AsyncRedactedWriter { let queued = 0; let dropped = 0; let failed = 0; let chain = Promise.resolve(); return { get health() { return { dropped, failed }; }, flush() { return chain; }, record(input) { let record: RedactedProbeRecord; try { record = canonicalizeRecord(input); } catch { failed += 1; return; } if (queued >= 1024) { dropped += 1; return; } queued += 1; chain = chain.then(() => store.append(record)).catch(() => { failed += 1; }).finally(() => { queued -= 1; }); } }; }
export function createCallbackObservationWriter(store: ProbeRecordStore, redactor: ProbeRedactor): CallbackObservationPort & Pick<AsyncRedactedWriter, "flush" | "health"> { const writer = createAsyncRedactedWriter(store); return { get health() { return writer.health; }, flush() { return writer.flush(); }, record(input: CallbackObservation) { try { writer.record(redactor.observation(input)); } catch { /* completed ACK */ } } }; }
